### ISSUE TITLE
"Commentaries Should we a Full Sentence."

### ISSUE THREAD

**Issue by HarderBetterFasterStronger** [bwplotka/my#13]
First off, great write-up!  [https://www.bwplotka.dev/2020/how-thanos-would-program-in-go/](How Thanos Would Program in Go)  I just found a typo (and thought it very ironic 😜 after comment):

> No Grammarly plugin for this yet ): (We wish).

This:

> Commentaries Should we a Full Sentence.

should be:

> Commentaries Should be a Full Sentence.

Thanks again for the write-up.

**Comment by bwplotka** [comment]
Amazing, sorry for lag, fixing now! Thanks :+1:
