### ISSUE TITLE
Invalid Go code in "How Thanos would program in Go"

### ISSUE THREAD

**Issue by nenad** [bwplotka/my#15]
In this blog post: https://www.bwplotka.dev/2020/how-thanos-would-program-in-go/ under the "Avoid :fire:" section where you explain DRY principles this code does not compile as there are two ways of accessing the `ID` and it fails with this error: `type Block has both field and method named ID`.

**Comment by bwplotka** [comment]
Ups missed, this, thanks for spotting, will fix (:
