### ISSUE TITLE
broken discord invite link

### ISSUE THREAD

**Issue by christian-korneck** [bwplotka/my#33]
hi there, this is just a friendly info that the discord link for the `Efficient Go` community as published in the Slides of your [Gophercon UK](https://www.youtube.com/watch?v=lOQbvikazMk) talk and your [blog post](https://www.bwplotka.dev/2021/efficient-go/) seems broken. Discord error: `Invite Invalid. This invite might be expired, or you might not have permission to join`.

(Thanks for the great talk btw).

**Comment by bwplotka** [comment]
Thanks a lot! Sorry lag, fixed now 🙈
